apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kargo-aws
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - server: '*'
    namespace: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  # Safer version (restrict sensitive resources):
  # namespaceResourceBlacklist:
  # - group: ''
  #   kind: 'ResourceQuota'
  # - group: ''
  #   kind: 'LimitRange'
  # - group: ''
  #   kind: 'NetworkPolicy'
  # - group: 'networking.k8s.io'
  #   kind: 'NetworkPolicy'