apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kargo-aws
  namespace: argocd
spec:
  sourceRepos:
  - '${GITOPS_REPO_URL}'
  destinations:
  - namespace: 'kargo-aws-*'
    server: https://kubernetes.default.svc