apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-aws
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: test
      - stage: uat
      - stage: prod
  template:
    metadata:
      name: kargo-aws-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-aws:{{stage}}
    spec:
      project: kargo-aws
      source:
        repoURL: ${GITOPS_REPO_URL}
        targetRevision: stage/{{stage}}
        path: .
      destination:
        server: https://kubernetes.default.svc
        namespace: kargo-aws-{{stage}}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true