apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-aws
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: test
      - stage: uat
      - stage: prod
  template:
    metadata:
      name: kargo-aws-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-aws:{{stage}}
    spec:
      project: kargo-aws
      source:
        repoURL: https://github.com/emilyxinyi/aws-kargo-crashcourse.git # REPLACE THIS: the URL of your git repository
        targetRevision: stage/{{stage}}
        path: .
      destination:
        name: argocd-agent # REPLACE THIS: the name of your destintation cluser
        namespace: kargo-aws-{{stage}}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true