apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-resources-aws-crashcourse
spec:
  project: kargo-aws
  source:
    repoURL: https://github.com/emilyxinyi/aws-kargo-crashcourse.git
    path: kargo-resources
  destination:
    name: kargo1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true